### ISSUE TITLE
Two quotes in generated javascript

### ISSUE THREAD

**Issue by henadzit** [splix/grails-spring-security-twitter#1]
Hi,

I found the issue, it is two quotes in generated javascript by the tag lib. It causes syntax error and prevents execution of javascript.
It is on line 72 in file TwitterAuthTagLib.groovy before semicolon:

out << "     window.href = '$authUrl'';"

Thanks,
Gennady Tsarik

**Comment by splix** [comment]
Oops, my bad. Thanks
