### ISSUE TITLE
Documentation seems wrong on settings

### ISSUE THREAD

**Issue by pledbrook** [splix/grails-spring-security-twitter#10]
The docs on the plugin portal page say that all the settings are in the `security.twitter` space, but looking at the code, it seems that they are all under `grails.plugins.springsecurity.twitter` (via calls to `SpringSecurityUtils.securityConfig`).

**Comment by rsato** [comment]
I also encountered this issue. https://gist.github.com/rsato/5317349

**Comment by splix** [comment]
Fixed at [0c304a5869e5261]

Please upgrade to plugin version **0.5**
