### ISSUE TITLE
Custom AuthenticationSuccessHandler not called on successful authentication via Twitter login.

### ISSUE THREAD

**Issue by keibro** [splix/grails-spring-security-twitter#18]
Upon connecting with Twitter, Twitter only exposes the username and name of the Twitter user. For applications that require the user's email also, the application must request these details itself.

Attempting to use the process outlined [here](http://omarello.com/2011/09/grails-custom-target-urls-after-login/), I have created a custom _SigninSuccessHandler_ (extends  SavedRequestAwareAuthenticationSuccessHandler), defined within _resources.groovy_ and linked to this plugin via the config setting:

``` javascript
grails.plugins.springsecurity.twitter.authenticationSuccessHandler = 'signinSuccessHandler'
```

The purpose of this _SigninSuccessHandler_ is to redirect to a new controller/page requesting the email details.

While it appears that the _SigninSuccessHanlder_ bean is instantiated, the _determineTargetUrl_ method is never called and Twitter login completes without hitting the email request page.

Is there anything else needed to successfully connect this handler?

**Comment by splix** [comment]
Looks like a bug, I'll take a look

**Comment by splix** [comment]
As I see http://omarello.com/2011/09/grails-custom-target-urls-after-login/ is outdated. Current Spring Security don't use `determineTargetUrl` method, see: https://github.com/SpringSource/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/SavedRequestAwareAuthenticationSuccessHandler.java

So, I suggest you to extend `SimpleUrlAuthenticationSuccessHandler`, and just override `onAuthenticationSuccess` method.

**Comment by keibro** [comment]
Many thanks - looks like this option will work!
