### ISSUE TITLE
Not able to configure default roles applied to new user.

### ISSUE THREAD

**Issue by keibro** [splix/grails-spring-security-twitter#19]
It appears that the _defaultRoleNames_ within [DefaultTwitterAuthDao](https://github.com/splix/grails-spring-security-twitter/blob/master/src/groovy/com/the6hours/grails/springsecurity/twitter/DefaultTwitterAuthDao.groovy#L38) are hard-coded.

The documentation notes that the _grails.plugins.springsecurity.twitter.autoCreate.roles_ can be used to define the roles to apply, but this does not appear to happen.

**Comment by splix** [comment]
fixed in v0.5.4
