### ISSUE TITLE
window.href works not for all browser

### ISSUE THREAD

**Issue by henadzit** [splix/grails-spring-security-twitter#2]
Hi,

I found one more issue. It is related to navigation to twitter authentication. Setting target URL like window.href = 'something' works not for all browsers.

Please replace line 72 in TwitterAuthTagLib.groovy with something like 

out << "     location.href = '$authUrl';"

More infromation: http://stackoverflow.com/questions/1537273/window-href-for-all-browser

Thanks,
Gennady Tsarik

**Comment by splix** [comment]
ok, thank you
