### ISSUE TITLE
Incorrect callback url being generated by default

### ISSUE THREAD

**Issue by gotomanners** [splix/grails-spring-security-twitter#4]
The callbackUrl is generated in TwitterAuthTaglib.groovy as follows:

```
String authFilter = conf.filter.processUrl
String callbackUrl = g.resource(file: authFilter, absolute: true)
```

Assiuming the app name is AuthModule, this callbackUrl then generated is:

/**AuthModule**alhost:8080/**AuthModule**/j_spring_twitter_security_check

So after authenticating with Twitter, an attempt is made to redirect back to this url, which never resolves.

**Comment by splix** [comment]
So, what URL did you get? 
What do you mean with `/AuthModulealhost`?

**Comment by gotomanners** [comment]
I'm not sure how `AuthModulealhost` is being generated, but its part of the invalid url.
Here i've attached a [Screenshot](http://i.imgur.com/5bcPQ) of the invalid url.

As for the configuration, everything is the default setting except for consumer key,  secret and popup.

**Comment by splix** [comment]
Hm, thats weird :( 
What you have for link generated by: `<g:createLink controller="ctrl" action="action" absolute="true">test</g:createLink>`?

**Comment by gotomanners** [comment]
`<g:createLink controller="ctrl" action="action" absolute="true">test</g:createLink>`

resolves to 

`http://localhost:8080/AuthModule/ctrl/action`

**Comment by gotomanners** [comment]
I was on previously on Resources 1.1.5.
Upgrading to Resources 1.1.6 seems to have resolved this issue.

**Comment by splix** [comment]
Ok, that's good. I also had have an another issue with Resources plugin.
