### ISSUE TITLE
Invalid Session Token? For Authentication

### ISSUE THREAD

**Issue by littleiffel** [splix/grails-spring-security-twitter#5]
Hi there, thanks for your work. But I have an issue, that very often I get this message when I try to log in to my app with twitter:

The request token for this page is invalid. It may have already been used, or expired because it is too old. Please go back to the site or application that sent you here and try again; it was probably just a mistake.

Is it possible that the session on grails expired? How  can I fix this issue? Shorter session timeouts? Or is there a general approach?

**Comment by splix** [comment]
Hi!

Seems that it's client side problem.

Please
- Sign out of twitter from your web browser
- Clear your cookies
- Sign into twitter on your web browser
- Then try connecting again

**Comment by littleiffel** [comment]
Hi, thanks for your quick reply. Ok that is working!

Is there a way to avoid this problem? For me I know what to do but the other users are blocked from registering on my site?

**Comment by splix** [comment]
I never has such problem before, but found that some people had (you can google this error message). I think it's really rare situation, and it's cannnot be fixed on server side, so you can handle this by some kind of faq page, or helpdesk, etc.
